### ISSUE TITLE
how to speed up the training process?

### ISSUE THREAD

**Issue by des-zhong** [reiniscimurs/DRL-robot-navigation#110]
Hi, really great projects. But i have some questions about the speeding up process of the training.
In your tutorial "https://medium.com/@reinis_86651/deep-reinforcement-learning-in-mobile-robot-navigation-tutorial-part5-some-extra-stuff-b744852345ac", you mentioned about changing the <real_time_update_rate> factor in TD3.world to say 2000 which will speed up the simulation by 2 times. But I've noticed that in velodyne_env.py file, the step function utilized time.sleep(TIME_DELTA) function to excute the given action for TIME_DELTA time. 
I don't think changing the <real_time_update_rate> factor will affect the total time for an episode which may still remain TIME_DELTA*episode_length
How to solve this? Thank you for your time

**Comment by reiniscimurs** [comment]
Hi, 
yes you would have to reduce the TIME_DELTA accordingly by factor of the increased the simulation time. Simulation time is separate from TIME_DELTA (which uses computer time). If you do not do this, you would still get sort of a speedup as your single step would be propagated for a longer time span, however that is not the intended behavior.
