### ISSUE TITLE
Simulation environment problem

### ISSUE THREAD

**Issue by pzhabc** [reiniscimurs/DRL-robot-navigation#132]
Hello, thank you for sharing. I created my own simulation environment when the network training was complete. I created a separate test environment to test, but I found that the robot simply couldn't navigate to the target point, not as well as a model trained using your simulation environment. Is this because my simulation environment is too simple (obstacles are fixed, no randomness)? Does the creation of a simulation environment seem critical?

**Comment by reiniscimurs** [comment]
Hi,

Randomness helps quite a lot in training. It is unclear to me if the different world was used in training as well or only in testing. In any case, I suggest checking if there are some major differences in how state is represented. For example, if your training world is small, lets say 5x5 meters, your trained sensor values will have seen only 5 meters max and trained on these values. Now, if you would put that kind of model in a 10x10 world, it would get confused. But further than that it is difficult to say anything without knowing what the worlds you used look like.
