### ISSUE TITLE
why my environment is empty

### ISSUE THREAD

**Issue by bb0928** [reiniscimurs/DRL-robot-navigation#134]
I followed the tutorial, when I launched train_velodyne_td3.py, RViz didn't produce any indoor environment, with error like:

[ERROR] [1712917359.424777513, 1.823000000]: Updating ModelState: model [cardboard_box_0] does not exist
[ERROR] [1712917359.424956752, 1.823000000]: Updating ModelState: model [cardboard_box_1] does not exist
[ERROR] [1712917359.425014172, 1.824000000]: Updating ModelState: model [cardboard_box_2] does not exist
[ERROR] [1712917359.425060643, 1.824000000]: Updating ModelState: model [cardboard_box_3] does not exist
[ERROR] [1712917438.270502562, 54.587000000]: Updating ModelState: model [cardboard_box_0] does not exist
[ERROR] [1712917438.270569909, 54.587000000]: Updating ModelState: model [cardboard_box_1] does not exist
[ERROR] [1712917438.270614372, 54.587000000]: Updating ModelState: model [cardboard_box_2] does not exist
[ERROR] [1712917438.270777024, 54.587000000]: Updating ModelState: model [cardboard_box_3] does not exist

what should I do? thanks a lot.

**Comment by bb0928** [comment]
Sorry I forgot to modify my path.

**Comment by TianYu-Geng** [comment]
Hi, I have the same problem. How did you fix it?

**Comment by reiniscimurs** [comment]
> Hi, I have the same problem. How did you fix it?

See any issue marked with resource path:
https://github.com/reiniscimurs/DRL-robot-navigation/issues?q=is%3Aissue%20state%3Aclosed%20label%3Aresouce_path

**Comment by TianYu-Geng** [comment]
Thanks a lot, I got the answer in [#16](https://github.com/reiniscimurs/DRL-robot-navigation/issues/16)！
