### ISSUE TITLE
My training seems unstart when running TD3 python script.

### ISSUE THREAD

**Issue by bb0928** [reiniscimurs/DRL-robot-navigation#135]
Excuse me, when I was running this in terminal:
(drl) bob@learndrl:~/DRL-robot-navigation/TD3$ python train_velodyne_td3.py 

after a rather long period of time, the output is merely:

[ WARN] [1712974645.355009737, 79.860000000]: TF_REPEATED_DATA ignoring data with redundant timestamp for frame base_link (parent odom) at time 79.860000 according to authority unknown_publisher
[ WARN] [1712974649.382994012, 80.394000000]: TF_REPEATED_DATA ignoring data with redundant timestamp for frame base_link (parent odom) at time 80.338000 according to authority unknown_publisher
[ WARN] [1712974651.153438329, 80.533000000]: TF_REPEATED_DATA ignoring data with redundant timestamp for frame base_link (parent odom) at time 80.533000 according to authority unknown_publisher
[ WARN] [1712974651.153624014, 80.533000000]: TF_REPEATED_DATA ignoring data with redundant timestamp for frame base_link (parent odom) at time 80.533000 according to authority unknown_publisher
[ WARN] [1712974651.153680456, 80.533000000]: TF_REPEATED_DATA ignoring data with redundant timestamp for frame base_link (parent odom) at time 80.533000 according to authority unknown_publisher
[ WARN] [1712974654.188870928, 80.880000000]: TF_REPEATED_DATA ignoring data with redundant timestamp for frame base_link (parent odom) at time 80.808000 according to authority unknown_publisher
[ WARN] [1712974659.761314725, 81.473000000]: TF_REPEATED_DATA ignoring data with redundant timestamp for frame base_link (parent odom) at time 81.451000 according to authority unknown_publisher
[ WARN] [1712974659.836830781, 81.525000000]: TF_REPEATED_DATA ignoring data with redundant timestamp for frame base_link (parent odom) at time 81.481000 according to authority unknown_publisher
[ WARN] [1712974964.540996422, 120.120000000]: TF_REPEATED_DATA ignoring data with redundant timestamp for frame base_link (parent odom) at time 120.120000 according to authority unknown_publisher
[ WARN] [1712974973.682190903, 124.882000000]: TF_REPEATED_DATA ignoring data with redundant timestamp for frame base_link (parent odom) at time 124.859000 according to authority unknown_publisher

I am wondering why it doesn't output data such as epochs? What's wrong with my environment setting? Thanks a lot.

**Comment by Shepherd010** [comment]
How did you solve it?
