### ISSUE TITLE
Questions about environment codes

### ISSUE THREAD

**Issue by namjiwon1023** [reiniscimurs/DRL-robot-navigation#146]
Dear @reiniscimurs

In the Melodic branch, Step function, one step publishes two times actions.

https://github.com/reiniscimurs/DRL-robot-navigation/blob/9a4d92ca41e370617baa4451f0a784f8ca5239ce/TD3/velodyne_env.py#L180

https://github.com/reiniscimurs/DRL-robot-navigation/blob/9a4d92ca41e370617baa4451f0a784f8ca5239ce/TD3/velodyne_env.py#L254

Is there any benefit in doing this? But this has been cancelled in Noetic.

Thanks you !

**Comment by reiniscimurs** [comment]
Hi,

This is just a mistake and the second publishing command does not actually get used. Since it is a Melodic branch, I have not updated it but it is not present in Noetic branch

**Comment by namjiwon1023** [comment]
Dear @reiniscimurs

That means that in the Melodic branch, the second self.vel_pub.publish(vel_cmd) （line 254） code is not actually used, right? Even if this environment is used, the results obtained are correct. its right?

Thanks you !

**Comment by reiniscimurs** [comment]
Yes, that is right. The second call will have no effect

**Comment by namjiwon1023** [comment]
Thank you for your prompt reply!

Thanks again for your contribution!
