### ISSUE TITLE
different world issue 

### ISSUE THREAD

**Issue by Seher-789** [reiniscimurs/DRL-robot-navigation#158]
hi, thank you for this amazing work. i want facing issue while using another world but it is displaying empty world. I placed the world file in same folder. 
![Screenshot from 2024-07-30 23-25-48](https://github.com/user-attachments/assets/af2b6c2f-5110-440a-bba1-b9bfccb1bd38)
![Screenshot from 2024-07-30 23-25-40](https://github.com/user-attachments/assets/2b76572b-857a-4373-b206-183d5fe4390e)

**Comment by reiniscimurs** [comment]
Hi,

Please use the template to submit the issue.

1. Have you checked that you have set up the sources correctly? What does the log output say?
2. Can you load your map in gazebo?

**Comment by Seher-789** [comment]
![Screenshot from 2024-08-03 21-06-22](https://github.com/user-attachments/assets/b9d3b4e1-5f37-4ae2-b92b-847afed1175c)
thank you for help. I did it by increase the time but now the problem is whenever i uplad the new world then i get this errors

**Comment by reiniscimurs** [comment]
The code expects there to be the cardboard boxes in the world to reset them to random positions. You can simply update the code, not to reset the objects that are not a partof your world file. Random box reset is explained in the tutorial: https://medium.com/@reinis_86651/deep-reinforcement-learning-in-mobile-robot-navigation-tutorial-part4-environment-7e4bc672f590

**Comment by Seher-789** [comment]
thank you so much. for your help i did it.
