### ISSUE TITLE
Issues with Gazebo and RVis. NOT LAUNCHING. 

### ISSUE THREAD

**Issue by Hoggaan** [reiniscimurs/DRL-robot-navigation#20]
Hi there, i was trying to run this training process, but Gazebo is not coming up, RViz is not running properly as well. However, Algorithm seems running. See pics below. Gazebo and RViz are working in other scenarios. Can you please look and figure out what is wrong. 
- Distro Ros Noetic. 
![Screenshot from 2022-06-23 21-25-00](https://user-images.githubusercontent.com/65222100/175344373-04404965-7285-4a86-b96f-77d3c7c0d6fd.png)
![Screenshot from 2022-06-23 21-25-37](https://user-images.githubusercontent.com/65222100/175344404-6f8ce52c-8b91-44f8-92f5-833faeb202e0.png)

**Comment by reiniscimurs** [comment]
Hi,

I see that you are cloning the repo in a separate folder and not in home folder. One thing to check would be if you have updated your export functions accordingly? 

Another thing is to check if you are not running into an issue similar to this: https://github.com/reiniscimurs/DRL-robot-navigation/issues/11

Gazebo GUI is turned off and will not start automatically. To turn it on, change the value here to true:
https://github.com/reiniscimurs/DRL-robot-navigation/blob/8e410ab6a05ff7852a09c692d9d6e1a3ec706fd1/catkin_ws/src/multi_robot_scenario/launch/empty_world.launch#L7

**Comment by Hoggaan** [comment]
Hello, Thanks for the timely reply. 
Gazebo is running now but very slow. The RViz is still not working properly. 

I refereed issue #11. The meaningful tip there was to wait for 30 minutes to download some models. I waited for 2 hours. No change. 

Please suggest any solutions possible. Note: my PC has no NVIDIA GUI capabilities.

**Comment by reiniscimurs** [comment]
Please provide the full log output from the terminal and describe your computer setup.

**Comment by Hoggaan** [comment]
Please see below. Full captures terminal and RViz. 

In your Launch files you used Robot_state_publisher, type= State_publisher which is deprecated and removed. I think that is what is causing the error. Thank you for your time. 

 * /rosdistro: noetic
 * /rosversion: 1.15.14
 
 Terminal Output - Captures
 
![1](https://user-images.githubusercontent.com/65222100/175476310-dad2618b-5f7a-4f97-8751-17fbbc1b8722.png)
![2](https://user-images.githubusercontent.com/65222100/175476320-db3bd217-9e6d-407a-bcc5-fc8d6e07084a.png)
![3](https://user-images.githubusercontent.com/65222100/175476328-43877aa9-ae0b-4911-b915-f5169ebd544e.png)
![4](https://user-images.githubusercontent.com/65222100/175476334-8397ed7e-465d-4c98-ab3e-2dc658bdc7ae.png)

RViz Captures  - This mybe helpful. 
![Rviz](https://user-images.githubusercontent.com/65222100/175476525-ea93ab9b-906e-4562-88b9-7ebe4f26c924.png)

**Comment by reiniscimurs** [comment]
Are you using the Noetic branch of this repo or the main branch? It looks like it is the main branch (Kinetic) which calls for static_state_publisher, which is not present in the ROS Noetic.
