### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by namjiwon1023** [reiniscimurs/DRL-robot-navigation#23]
Thank you for your contribution!!

When I run the command 'python3 velodyne_td3.py', agent's training episode steps is not displayed.

And the following error will appear.

![image](https://user-images.githubusercontent.com/62288559/181230682-a5275547-4652-430c-9e87-21a870fa3ae7.png)

How can I solve this problem, waiting for your reply.

**Comment by reiniscimurs** [comment]
Hi,

Can you show the full output from the terminal?
Which ROS version are you using?

**Comment by namjiwon1023** [comment]
Hi, thanks for replying so quickly！

OS : Mint 19 (Ubuntu 18.04)
ROS version : Melodic

![image](https://user-images.githubusercontent.com/62288559/181256657-0c16c513-9a09-477b-940b-aa7db42bc339.png)
![image](https://user-images.githubusercontent.com/62288559/181256770-938114eb-5c39-46a5-85ef-3d96954df623.png)

After a period of time, information such as episode, mean_reward can be displayed. But I don't know what the impact of the "Spawn service failed" error will be.

**Comment by reiniscimurs** [comment]
So as it appears to me the rviz is trying to spawn the robot model but timing out and essentially ignoring the robot model in the end. You can try increasing the time that neural network waits for the environment to start here: https://github.com/reiniscimurs/DRL-robot-navigation/blob/d51438aea0dd8404ae7a633dcfc4f5f96e54f569/TD3/velodyne_td3.py#L210

See if that helps. 
What is the output from the rviz screen?

Also, it seems that it is training just fine, just the robot model is not getting loaded in rviz.
You could check this by opening the gazebo simulator during run time.
Start the training, then open a separate terminal window and run command `gzclient`
This should open gazebo and robot motion should be visible there.

**Comment by namjiwon1023** [comment]
I didn't make any changes.

Now the agent has been trained for 20 hours, The agent has learned a policy to find the target.

![image](https://user-images.githubusercontent.com/62288559/181470735-3973cb42-8b53-491f-a219-f59e6f368f66.png)

rviz screen output:

![image](https://user-images.githubusercontent.com/62288559/181471620-d6898f10-9a54-42c3-aea6-de7a6eb58919.png)

I will continue my research in your direction.

I'm very much obliged to you.
