### ISSUE TITLE
simulation train

### ISSUE THREAD

**Issue by wxmshiguang** [reiniscimurs/DRL-robot-navigation#3]
When I configure the environment variables and run the training
$ cd ~/DRL-robot-navigation/TD3
$ python3 velodyne_td3.py
![QQ图片20211127145736](https://user-images.githubusercontent.com/37468836/143671584-7818a3b3-0009-4276-8bb1-90821b7346b7.jpg)
I encountered the above error. I use gazebo9, ROS is melodic.
I am new to ROS and I wonder if there is a problem with the  input command.
And What should I type to implement the training example in README.md.
Thank you very much.

**Comment by reiniscimurs** [comment]
Does the program not run after encountering the "QObject" issue?

I don't have the access to the system right now, but if I remember correctly, this issue does not impede the training process and you can ignore it. Let me know if the training is not happening or the robot is not moving after just simply ignoring the issue. Then I will try to set up the system again, but it might take some time.

**Comment by wxmshiguang** [comment]
Yes，The robot is moving normally，but the output of training in following figure does not appear.
![image](https://user-images.githubusercontent.com/37468836/143678806-679e70f8-d82f-4279-9cb0-4eb51f941c16.png)
Do I need to input any other instructions？

**Comment by reiniscimurs** [comment]
No need to do anything. You just need to wait.

Validation happens only after certain amount of steps. After validation is complete, the "Average reward" will also be output to the terminal.
If you'll go through the velodyne_td3.py file you will notice a variable:
`eval_freq = 5e3  # After how many steps to perform the evaluation`
This is how many steps it will take to perform the validation and subsequently give similar output to the terminal.
You can reduce it to perform validation more often and have the output.

**Comment by wxmshiguang** [comment]
Thank you very much for your guidance. I have similar output.

**Comment by reiniscimurs** [comment]
That's great to hear. I'll close the issue then.
