### ISSUE TITLE
I got stack at somewhere. Help me please. 

### ISSUE THREAD

**Issue by Hoggaan** [reiniscimurs/DRL-robot-navigation#33]
Dear Reiniscimurs, 

Few months back, with your help i reproduced your work. Thanks. Now, i was trying to change for the robot model you used. This time i am trying to use Turtlebot3[Burger or waffle]. I am successful partially as when i run the code, Gazebo loads the world and spawns the model. However, the issue is the training is not starting. look the screenshot below. 

ISSUES:
* Laser is not visible even if i enabled 'True' in the Xacro file.
* The program stops as you can see in the screenshot. 

I guess i do not subscribe some topics. But how?
![Screenshot from 2022-09-14 15-20-48](https://user-images.githubusercontent.com/65222100/190124744-b6e9af54-4b46-437b-acf1-6158c87a5528.png)

**Comment by reiniscimurs** [comment]
Hi,

It will be hard to see what is wrong from the output here. Please provide the rqt tree of the robot and the published ros topic list when you run the program.

Can also include the xacro file of the robot to see what is happening.

**Comment by Hoggaan** [comment]
* Xarc Files - Two most important: - Can't upload them here but will take vew screenshots from them. 
![Screenshot from 2022-09-15 14-24-28](https://user-images.githubusercontent.com/65222100/190361314-3fedeb32-5c1e-4985-b8b2-658e6c7e1281.png)
![Screenshot from 2022-09-15 14-24-40](https://user-images.githubusercontent.com/65222100/190361325-4d3394c8-0e84-4c0d-97d7-1a07ed6fd817.png)
![Screenshot from 2022-09-15 14-24-48](https://user-images.githubusercontent.com/65222100/190361332-4b9d466e-b31b-4a4c-85c8-daafccfe06ec.png)
![Screenshot from 2022-09-15 14-24-55](https://user-images.githubusercontent.com/65222100/190361337-6f842892-11be-49c7-94ff-05e70111149c.png)
![Screenshot from 2022-09-15 14-25-01](https://user-images.githubusercontent.com/65222100/190361344-05019035-778f-4acb-993a-06337b71da06.png)
![Screenshot from 2022-09-15 14-25-09](https://user-images.githubusercontent.com/65222100/190361351-6561da12-cb78-4a1e-8d0e-9ecf9f353ad5.png)
![Screenshot from 2022-09-15 14-25-15](https://user-images.githubusercontent.com/65222100/190361355-b8c8b549-d176-4fb9-baff-fc484844c518.png)
![Screenshot from 2022-09-15 14-25-26](https://user-images.githubusercontent.com/65222100/190361362-cd50116c-20e0-4eef-b682-5b9dbf4c7c9e.png)
![Screenshot from 2022-09-15 14-25-35](https://user-images.githubusercontent.com/65222100/190361371-bb59b37f-232f-48d5-8795-c6a5d1a94aa1.png)
![Screenshot from 2022-09-15 14-25-41](https://user-images.githubusercontent.com/65222100/190361380-03f5dd55-e836-4d10-af82-63809eb8fb9b.png)
![Screenshot from 2022-09-15 14-25-47](https://user-images.githubusercontent.com/65222100/190361389-579c3c8b-44b5-4439-9d7f-7fe398268591.png)
![Screenshot from 2022-09-15 14-25-52](https://user-images.githubusercontent.com/65222100/190361395-5197bb9b-bec2-4969-835e-a1f36fc638a4.png)
![Screenshot from 2022-09-15 14-25-58](https://user-images.githubusercontent.com/65222100/190361403-d456c558-3e59-4e46-a188-2ba746792a8f.png)
![Screenshot from 2022-09-15 14-26-04](https://user-images.githubusercontent.com/65222100/190361415-ab4ae974-6910-4dd1-a95c-dea5cd50b3ab.png)


* Useful Screenshots
![Screenshot from 2022-09-15 14-13-25](https://user-images.githubusercontent.com/65222100/190359234-b82c4de6-f53f-45de-96d3-669e735e6156.png)
![Uploading Screenshot from 2022-09-15 14-13-35.png…
![Screenshot from 2022-09-15 14-19-09](https://user-images.githubusercontent.com/65222100/190359636-6ddaa2a4-0cb1-4ec3-8cd8-77254db70bba.png)
]
![last_graph](https://user-images.githubusercontent.com/65222100/190359204-01508000-4c91-45f8-86c5-42c1ca9ce2df.png)
![Screenshot from 2022-09-15 14-13-10](https://user-images.githubusercontent.com/65222100/190359224-7c504713-b7d3-48bf-ae0f-875ab07b1608.png)

**Comment by Hoggaan** [comment]
This is your rqt_graph:
![rosgraph](https://user-images.githubusercontent.com/65222100/190361721-15c46b61-111b-419f-95ce-befa61fb3fe4.png)

**Comment by Hoggaan** [comment]
As i closely watched the robot is circulating in it's position. 
![Screenshot from 2022-09-15 14-36-44](https://user-images.githubusercontent.com/65222100/190363949-f54f2916-6ab3-4637-890c-468bea572b06.png)
![Screenshot from 2022-09-15 14-37-53](https://user-images.githubusercontent.com/65222100/190363960-e9a2b8eb-578f-49e2-9371-2212fe3d8ba3.png)

**Comment by reiniscimurs** [comment]
Hi,
I don't see any robot related topics in the rqt tree. What is your `rostopic list` output? What rostopics are running?

Also, what is the TF_tree in rqt? (When opening rqt go to Plugins->Visualization->TF Tree)

The xacro seems that will not be particularly helpful here. When steps did you take to change the robot model?

**Comment by Hoggaan** [comment]
This is the rqt_tf_tree of your project:
![frames_other](https://user-images.githubusercontent.com/65222100/190847792-0c3df8ed-0f8e-4fba-8d22-b90bdc698e60.png)
This is the mine: 
![frames](https://user-images.githubusercontent.com/65222100/190847832-ad909189-028d-459b-9166-a0ce25c18b19.png)

ROSTOPIC LIST
![Screenshot from 2022-09-17 14-03-02](https://user-images.githubusercontent.com/65222100/190848047-f9c2d014-be70-4ffa-ae95-cef0c8f30467.png)

What steps? answer:

I download tutlebot3 from github. Then i just taken the Turtlebot3_Description packet which i added to my project. Then i made launch files which are typically the same as yours. I edited the files they we pointing to files i wanted for example instead of calling Pioneerxrd.xacro i am calling turtlebot_burger.xacro.

Project is running without an error and gazebo spawns the model into the environment. Even the model is circling in it's position. However, i did not set up publishers and subscribers very well. What is your suggestion?

**Comment by reiniscimurs** [comment]
Judging by the TF tree, It seems that the velodyne laser is not attached to your robot base. So it will not move when the robot is moving. That means that every input will be the same, so output will also be the same from the network (which would explain the rotating on the spot motion). See if it is so. A simple way to do so is to add the velodyne pointcloud in rviz (which should already be there, but I do not see the output in your screenshot) and see what comes out visually on the screen.

**Comment by Hoggaan** [comment]
Hello thanks. I added the velodyne. But look the picture the two hardware are separate physically. Still the robot is not apple to move. 
![fr_new](https://user-images.githubusercontent.com/65222100/190897653-5c3fb26f-f0a8-4e22-b20b-386d0860229f.png)
![Screenshot from 2022-09-18 15-50-30](https://user-images.githubusercontent.com/65222100/190897664-84f95d36-1809-45cc-b48d-12c8f755ffe6.png)

**Comment by reiniscimurs** [comment]
The velodyne laser might appear apart from the robot, depending on how you have described their connection. It might be "floating" above the robot, that should not be an issue. But does the laser move around together with the robot and move around the environment?

Can you share the code, where you attached the velodyne puck?

If attatching the velodyne puck does not work, i will try to implement turtlebot base in the repo (but not earlier than next week)

**Comment by Hoggaan** [comment]
<xacro:VLP-16 parent="base_link" name="velodyne" topic="/velodyne_points" hz="10" samples="360" gpu="false" min_angle="-1.57" max_angle="1.57" min_range="0.1">
    <origin xyz="0.125 0 0.25" rpy="0 0 0" />
  </xacro:VLP-16>

I copied this part from your Pioneer Xacro file to my Urdf xacro file. The robot is not moving. I did not get any other help from the internet that is why i am stack for almost a week. This is the intial implement of my research project. My focus is multi-robot task allocation. Please share on your experience what you think one may need to know to do that project.

**Comment by Hoggaan** [comment]
Hello. 
I would like to tell you that the robot started moving. The problem was topics. I suspected that the Gazebo was publishing topics different from those of your world. However, i tried several times to make things right in terms of topics. But if anyone of them is not publishing or subscribing the right topic nothing will work. Wonderful!

Thanks for your time.
