### ISSUE TITLE
Problem with rviz

### ISSUE THREAD

**Issue by 525753936** [reiniscimurs/DRL-robot-navigation#53]
Hi, thanks for sharing your amazing work!
I got a problem when I am trying to replace the robot  with my own robot model, it seems that my tf coordinates had some problems. Here you can see the tf_graph and the rviz errors.
Could you give me some suggestions to enlighten me to address these problems, since I am new to Ros? 
![tf_graph](https://user-images.githubusercontent.com/99471863/230754620-26a5b34a-e254-4ffc-bd16-8831237ccd5d.png)
![2023-04-09 12-31-56 的屏幕截图](https://user-images.githubusercontent.com/99471863/230754626-49c942ad-fbb5-40f6-84b3-0aee388f16fa.png)

**Comment by 525753936** [comment]
My Ros Verision is melodic18.04，and I can run your melodic version pioneer3dx robot in both rviz and gazebo.

**Comment by reiniscimurs** [comment]
Hi,

Please post the rqt tf tree to see if all the links are connected properly

**Comment by 525753936** [comment]
Hi,
here is my tf_tree shown.
![frames](https://user-images.githubusercontent.com/99471863/230783204-1872a6bd-8aa2-459a-9b27-8d111b4520f0.png)

**Comment by 525753936** [comment]
hi I change my code and robot model to the ROS-Noetic version, and i check my tf tree carefully, and it looks like running well. but just a few seconds after launch the environment, the program stuck there. And the robot stopped moving ,i checked the tf tree again, that i found the /odom was vanished, could you gave me some suggestions ?

![frames](https://user-images.githubusercontent.com/99471863/230906575-ab6933e4-4d98-4e4d-9f99-f5b658705ccb.png)
![2023-04-10 21-00-57 的屏幕截图](https://user-images.githubusercontent.com/99471863/230906589-44129bdb-e142-4d11-a347-0c727ac0556a.png)
![2023-04-10 20-58-28 的屏幕截图](https://user-images.githubusercontent.com/99471863/230906592-a7e55728-ac47-4444-9dad-c3d9f8f81958.png)
![111](https://user-images.githubusercontent.com/99471863/230906598-973affaa-9bb0-4152-9292-3a3d66d21250.png)
