### ISSUE TITLE
Does ROS2 version of this program for turtlebot3 exists?

### ISSUE THREAD

**Issue by GitHubGM** [reiniscimurs/DRL-robot-navigation#65]
I have turtlebot3 with ROS2 foxy, I can upgrade to humble. I wanted to try on it. Since ROS 1 is on EOL state, will this program be translated to ROS2?

**Comment by reiniscimurs** [comment]
There is no ROS2 implementation for this repo. I have no immediate plans to migrate to ROS2.

Contributions are always welcome though.
