### ISSUE TITLE
Robot goes around in circles. 

### ISSUE THREAD

**Issue by Talha771** [reiniscimurs/DRL-robot-navigation#66]
I cloned this repo and ran the training, however, there has been no noticable improvement in the reward and the robot just goes around rotating, and does not move at all. Am I missing setting some parameters or getting overly stressed way too early in the training process ? 

![image](https://github.com/reiniscimurs/DRL-robot-navigation/assets/77672851/5cd71ec1-0ac6-4778-93d7-f6a2692324df)

It is moving a bit, but mainly just in circles, Also, I'm running this on an Titan RTX and it trained around 52 epochs in around 15 hours, I think its taking longer than it should, but I don't know how to change that.

**Comment by reiniscimurs** [comment]
Hi,

It could just e that you need to change the seed for the initialization of the network.
See explanation here: https://github.com/reiniscimurs/DRL-robot-navigation/issues/19
Let me know if that does not work, then we can look into it deeper.

**Comment by Talha771** [comment]
Thank you, will try that. Also thank you for being so responsive

**Comment by Talha771** [comment]
This worked perfectly.

**Comment by DanDan996** [comment]
> This worked perfectly.

Hi, can you please tell me what your seed value is set at? I have set many values without good results and end up in the situation described in your question.

**Comment by vamsi8106** [comment]
> This worked perfectly.

Please may I know which value of seed has worked good I have tried many values but no improvement.
