### ISSUE TITLE
critic network

### ISSUE THREAD

**Issue by AgentEXPL** [reiniscimurs/DRL-robot-navigation#7]
https://github.com/reiniscimurs/DRL-robot-navigation/blob/dea37acfc65f702f7fa792787e09602416cf85d4/TD3/velodyne_td3.py#L76

The above code is used for assembling the features from action and the features from state. Is this trick an normal operation in Actor-Critic framework? Would you like to introduce more about the motivation? Why not use the average of  self.layer_2_s(s1) and self.layer_2_a(a)?

**Comment by reiniscimurs** [comment]
Take a look at the explanation [here](https://pemami4911.github.io/blog/2016/08/21/ddpg-rl.html)
This proved to work better for me than other methods.
