### ISSUE TITLE
Problems with the training process

### ISSUE THREAD

**Issue by yuyuanyaya** [reiniscimurs/DRL-robot-navigation#72]
Hi , thank you for your great project. I had some problems when trying to reproduce your work. I followed the readme documentation to configure the environment and dependencies.

Here is my system setup:
Ubuntu 20.04 LTS
ROS noetic
python 3.8.10
pytorch 2.0.1+cpu
tensorboard 2.13.0
codes are cloned from main branch
Here's a picture of my (.bashrc)
![Ubuntu 20 04 6-2023-07-28-14-50-10](https://github.com/reiniscimurs/DRL-robot-navigation/assets/115441391/5256480e-78bb-4410-ac07-99ce714deeeb)
![Ubuntu 20 04 6-2023-07-28-14-49-17](https://github.com/reiniscimurs/DRL-robot-navigation/assets/115441391/12495209-fa91-45df-92e0-0d14fe3c214c)
This is my cmake operation
![Ubuntu 20 04 6-2023-07-28-14-15-38](https://github.com/reiniscimurs/DRL-robot-navigation/assets/115441391/b2a6669c-a62e-49b9-8eba-a9f3cb93ea4d)
![Ubuntu 20 04 6-2023-07-28-14-15-51](https://github.com/reiniscimurs/DRL-robot-navigation/assets/115441391/118b679f-8cd6-450d-bc6c-9a9d2fa89324)
This is my train operation
![Ubuntu 20 04 6-2023-07-28-14-15-11](https://github.com/reiniscimurs/DRL-robot-navigation/assets/115441391/fb4356fb-79da-4e7e-be72-916a8ab1afd3)
![Ubuntu 20 04 6-2023-07-28-15-21-17](https://github.com/reiniscimurs/DRL-robot-navigation/assets/115441391/ee70898d-df9f-4da9-a9de-8cc2c39dfce8)
![Ubuntu 20 04 6-2023-07-28-15-27-10](https://github.com/reiniscimurs/DRL-robot-navigation/assets/115441391/a6556a18-e0a3-452f-bd6e-cd752ff0f3f0)
At this point there is a problem, and gazebo won't start, can you help me?

**Comment by reiniscimurs** [comment]
Hi, Thank you very much for the detailed logs and description. It is very much appreciated. Are you running the repo in a clean install of ROS? If that is the case, it might be that ROS is downloading some models in the background and not able to start the training without them. In such a case, I suggest letting the training "run" for some 20 minutes and then restarting to see if the models are downloaded.

Other option is that odometer data is read before the robot has been spawned. You can try increasing the time to wait for all the things to have spawned in the gazebo.
https://github.com/reiniscimurs/DRL-robot-navigation/blob/943186fb7f1890700ce215951e92d5cb92031d14/TD3/train_velodyne_td3.py#L253

**Comment by yuyuanyaya** [comment]
Hi，thank you very much for the suggestion, now it is able to run in rviz. But it is not
![Ubuntu 20 04 6-2023-07-29-13-41-02](https://github.com/reiniscimurs/DRL-robot-navigation/assets/115441391/82ff90a7-07b8-4f7a-b308-da5bfa906571)
 to display the gazebo environment and the camera image in rviz is also grayed out and no image is displayed. How can I solve this problem?

**Comment by reiniscimurs** [comment]
Did you try launching gazebo? (By default it will not be launched automatically). If so, what is the error that comes up?

**Comment by wzg98** [comment]
> 您好，非常感谢您的建议，现在已经可以在rviz中运行了。但并不是 显示gazebo环境，rviz中的摄像头图像也是灰显的，没有图像显示。我怎么解决这个问题？ ![Ubuntu 20 04 6-2023-07-29-13-41-02](https://user-images.githubusercontent.com/115441391/256967498-82ff90a7-07b8-4f7a-b308-da5bfa906571.png)
I have encountered the same issue with rviz as you. How did you solve it? Thank you very much.
