### ISSUE TITLE
Something wrong when command "source devel_isolated/setup.bash"

### ISSUE THREAD

**Issue by BAp3r** [reiniscimurs/DRL-robot-navigation#74]
I reinstalled wsl, this time when running the command “source devel_isolated/setup.bash,” the system prompts that “source devel_isolated/setup.bash,”, and naturally I can't start the training, can you help me with this?
![20230822220032](https://github.com/reiniscimurs/DRL-robot-navigation/assets/87560912/5876d88e-4dd5-4190-999d-26e7d0adca25)
![20230822220101](https://github.com/reiniscimurs/DRL-robot-navigation/assets/87560912/c630823f-7431-4280-a1c2-e3b52ee48a45)

**Comment by reiniscimurs** [comment]
Hi

Since you are compiling with catkin_make instead of catkin_make_isolated, your source file will be stored in devel/ instead of devel_isolated/ so you have to source it from devel/

**Comment by BAp3r** [comment]
Thanks for your reply, it works.
