### ISSUE TITLE
catkin_make_isolated error

### ISSUE THREAD

**Issue by peipei518** [reiniscimurs/DRL-robot-navigation#77]
Hello, thank you for sharing. I ran the project on ubuntu18.04，When I was compiling this project, the following error occurred  :error: no matching function for call to ‘google::protobuf::internal::ArenaStringPtr::GetNoArena(const string*) const’，May I ask how to solve it

**Comment by reiniscimurs** [comment]
Hi

Which branch of the repo are you trying to install?

**Comment by merak0514** [comment]
I had the same problem with python 3.11.
Switch back to python 3.8 solves it.
