### ISSUE TITLE
Problem with the starting training

### ISSUE THREAD

**Issue by Mehmet-Gozukucuk** [reiniscimurs/DRL-robot-navigation#83]
First of all, Thank you for this great project . I am trying to train the agent you created with the codes you provided I did everything as you mentioned then I was able to train the agent but I had to stop the training. I tried to do it again a few times but I couldn't do it . if I export this

 export ROS_HOSTNAME=localhost
export ROS_MASTER_URI=http://localhost:11311
export ROS_PORT_SIM=11311
export GAZEBO_RESOURCE_PATH=~<PATH_TO_FOLDER>/DRL-robot-navigation/catkin_ws/src/multi_robot_scenario/launch
source ~/.bashrc
cd ~<PATH_TO_FOLDER>/DRL-robot-navigation/catkin_ws
source devel_isolated/setup.bash 

commands in the terminal and then start training I got this ;
![Screenshot from 2023-11-09 07-46-24](https://github.com/reiniscimurs/DRL-robot-navigation/assets/140517314/fd1c8b2a-fcfc-4965-9dfb-65bbf86ae095)
![Screenshot from 2023-11-09 07-46-22](https://github.com/reiniscimurs/DRL-robot-navigation/assets/140517314/509218a0-8ce9-4cd4-992e-d6e28a3d28ad)

in my terminal . it says roscore on the top and nothing happens.

When I try to do it without exporting this commands;

export ROS_HOSTNAME=localhost
export ROS_MASTER_URI=http://localhost:11311
export ROS_PORT_SIM=11311
export GAZEBO_RESOURCE_PATH=~<PATH_TO_FOLDER>/DRL-robot-navigation/catkin_ws/src/multi_robot_scenario/launch
source ~/.bashrc
cd ~<PATH_TO_FOLDER>/DRL-robot-navigation/catkin_ws
source devel_isolated/setup.bash 

  I get something but I have some problems I see in my terminal and the robot goes randomly there is no obtacles and nothing in camera. 
![Screenshot from 2023-11-09 07-11-23](https://github.com/reiniscimurs/DRL-robot-navigation/assets/140517314/7068787f-54d4-4743-8412-3ca35345d151)
![Screenshot from 2023-11-09 07-28-37](https://github.com/reiniscimurs/DRL-robot-navigation/assets/140517314/98ceac90-fc05-47c7-b91b-64ebb51330ff)
![Screenshot from 2023-11-09 07-28-49](https://github.com/reiniscimurs/DRL-robot-navigation/assets/140517314/e5e66564-b011-4ee3-bcbe-c0869413a698)

![Screenshot from 2023-11-09 07-28-57](https://github.com/reiniscimurs/DRL-robot-navigation/assets/140517314/25990e15-c55c-443c-b28f-f79053aa99b2)
so I am stuck at this point and I can't train the agent . if you can help me with this problem I would be so glad. Thanks in advance.
additionally this is my .bashrc file
![Screenshot from 2023-11-09 07-58-49](https://github.com/reiniscimurs/DRL-robot-navigation/assets/140517314/30e1548c-c90b-4367-8e0c-8901dc389988)

**Comment by reiniscimurs** [comment]
Hi,

If you do not export the export `GAZEBO_RESOURCE_PATH ` the gazebo simulation will not be able to find where the world file is located. So you end up loading just an empty world file. You could just add these exports to your source file.

For ROS not starting issues I do not know, what issue you might be facing. Generally there should be no problem in just passing these commands in the terminal, given that you closed your previous training properly and stopped all ros actions. Did you try simply restarting your computer and starting the training? This would ensure that any ros background process has been closed.

**Comment by Mehmet-Gozukucuk** [comment]
Yes I tried to restart my computer

**Comment by Mehmet-Gozukucuk** [comment]
I solved the problem thank you :)

**Comment by reiniscimurs** [comment]
> I solved the problem thank you :)

Great!
What was the solution? Would be good to know as it could help others if they encounter a similar situation.

**Comment by Mehmet-Gozukucuk** [comment]
of course, I am not sure if it was the problem but it was okay after  I delete the commands in my bashrc file . As you see I had some commands starting from 121 line about conda . I delete all of them and redo the steps . Finally it is working perfectly 
![Screenshot from 2023-11-09 11-44-42](https://github.com/reiniscimurs/DRL-robot-navigation/assets/140517314/3d84eb0b-29a2-467d-b958-510837d64071)
![Screenshot from 2023-11-09 11-44-55](https://github.com/reiniscimurs/DRL-robot-navigation/assets/140517314/6da3b18f-8fe0-408e-9c43-4f25b49008ed)

**Comment by manishvvit** [comment]
Hello sir
I am getting the same error , can you please help me out with training process.
![Screenshot from 2024-02-23 10-12-10](https://github.com/reiniscimurs/DRL-robot-navigation/assets/145148421/bef6c203-b48f-4b8f-a017-7008465c6635)
