### ISSUE TITLE
Global Navigation

### ISSUE THREAD

**Issue by stars113** [reiniscimurs/DRL-robot-navigation#85]
Hi Reinis Cimurs,

I hope this message finds you well. I've been exploring your Goal-Driven Autonomous Exploration Through Deep Reinforcement Learning on GitHub and I am quite impressed with the work you've done.

I noticed that there seems to be a lack of code related to global navigation in the repository. Could you kindly provide more information about the absence of global navigation code?

I am particularly interested in understanding how global navigation could be integrated into the project and if there are any specific considerations or challenges you have encountered in this regard.

Thank you for your time, and I appreciate your efforts in making this project open-source.

                                                                                                                          Best regards

**Comment by reiniscimurs** [comment]
1. You would essentially just need to update the GDAM.py file there to use pytorch. You could either update that file to use pytorch functionality or unpdate the DRL-navigation test file to pass the arguments and use the env file from GDAE.
2. Other way around. You would have to update GDAE to use the trained model policy from this repo.

That should replicate GDAE with using policy of the current repo.
