### ISSUE TITLE
Problem with the starting training

### ISSUE THREAD

**Issue by Ethan0207** [reiniscimurs/DRL-robot-navigation#94]
First of all, thank you for your sharing. This a great project .I am trying to train the agent you created with the codes you provided and I did everything as you mentioned. But I have a problem about it. When I start training, it just start only “roscore launched”.I have no idea. Is there something wrong with the environment?
![6U1B182 {IIP5) K()B}4DD_tmb](https://github.com/reiniscimurs/DRL-robot-navigation/assets/138771150/19b41056-0ff7-4465-8966-a7dc19bca329)

**Comment by reiniscimurs** [comment]
Hi,

Yes, seems there is an issue with your ros launch. The program should automatically launch roscore and you should see the logs.
Which repo version and which ros version are you using?

**Comment by Ethan0207** [comment]
Thank you very much for your reply. My ROS version is 20.04. But repo has not been installed.  Does this need to be installed?

**Comment by reiniscimurs** [comment]
Repo does not need to be installed, just compiled. It does however have 3 different branches and I would need to know which branch you have cloned.

What seems to be the issue that roscore is not being launched. Can you launch roscore on its own in an empty terminal?

**Comment by Ethan0207** [comment]
Thank you for your reply. Firstly, I have cloned "main". And I can launch roscore on its own in an empty terminal
![branch](https://github.com/reiniscimurs/DRL-robot-navigation/assets/138771150/40e95ab0-c2aa-4c51-a8b4-78c44efc13e9)
![roscore](https://github.com/reiniscimurs/DRL-robot-navigation/assets/138771150/7c95ef42-5f6e-4091-98d9-be5110c8fd80)

**Comment by reiniscimurs** [comment]
Seems to me that `subprocess.Popen(["roscore", "-p", port])` is not working in your setup. You could test it in a dummy script or debug in the current setup.

Alternatively, you can manually start roscore and the gazebo before running the training script.

**Comment by Ethan0207** [comment]
Hello，thank you for your reply. These days, I try to solve my problems , but it still has some mistakes .These mistakes are similar to the issue of "Problem with the starting training" mentioned by the friend below.
When I try to do it without exporting this commands;
export ROS_HOSTNAME=localhost
export ROS_MASTER_URI=http://localhost:11311/
export ROS_PORT_SIM=11311
export GAZEBO_RESOURCE_PATH=~<PATH_TO_FOLDER>/DRL-robot-navigation/catkin_ws/src/multi_robot_scenario/launch
source ~/.bashrc
cd ~<PATH_TO_FOLDER>/DRL-robot-navigation/catkin_ws
source devel_isolated/setup.bash
In my terminal . it says roscore on the top and nothing happens.
![Ubuntu12 28 1](https://github.com/reiniscimurs/DRL-robot-navigation/assets/138771150/48ac64d5-5170-4736-bf60-60453d558801)
if I export this
export ROS_HOSTNAME=localhost
export ROS_MASTER_URI=http://localhost:11311/
export ROS_PORT_SIM=11311
export GAZEBO_RESOURCE_PATH=~<PATH_TO_FOLDER>/DRL-robot-navigation/catkin_ws/src/multi_robot_scenario/launch
source ~/.bashrc
cd ~<PATH_TO_FOLDER>/DRL-robot-navigation/catkin_ws
source devel_isolated/setup.bash
In my terminal . it still says roscore on the top and nothing happens.
![Ubuntu12 28 2](https://github.com/reiniscimurs/DRL-robot-navigation/assets/138771150/bc4e2127-a016-4302-b4b1-5331da866080)
So I am stuck at this point and I can't train the agent . If you can help me with this problem I would be so glad. Thanks in advance.
additionally this is my .bashrc file
![Ubuntu12 28 3](https://github.com/reiniscimurs/DRL-robot-navigation/assets/138771150/88e775fe-b479-427b-8c9e-8d4fdaff4cd1)
