### ISSUE TITLE
Problem with  training

### ISSUE THREAD

**Issue by Ethan0207** [reiniscimurs/DRL-robot-navigation#97]
Hello. These days, I try to solve my problems , but it still has some mistakes .These mistakes are similar to the issue of "Problem with the starting training" mentioned by the friend below.
When I try to do it without exporting this commands;
export ROS_HOSTNAME=localhost
export ROS_MASTER_URI=http://localhost:11311/
export ROS_PORT_SIM=11311
export GAZEBO_RESOURCE_PATH=~<PATH_TO_FOLDER>/DRL-robot-navigation/catkin_ws/src/multi_robot_scenario/launch
source ~/.bashrc
cd ~<PATH_TO_FOLDER>/DRL-robot-navigation/catkin_ws
source devel_isolated/setup.bash
In my terminal . it says roscore on the top and nothing happens.
![Ubuntu12 28 1](https://github.com/reiniscimurs/DRL-robot-navigation/assets/138771150/742676a2-b184-40b5-927d-efc092fd68e1)
if I export this
In my terminal . it still says roscore on the top and nothing happens.
![Ubuntu12 28 2](https://github.com/reiniscimurs/DRL-robot-navigation/assets/138771150/d480bc98-44df-4486-89c1-ebbf78ce1bef)
So I am stuck at this point and I can't train the agent . If you can help me with this problem I would be so glad. Thanks in advance.
additionally this is my .bashrc file
![Ubuntu12 28 3](https://github.com/reiniscimurs/DRL-robot-navigation/assets/138771150/ac7c1b50-31f9-4e90-80d8-a09a87e45759)

**Comment by reiniscimurs** [comment]
Hi,

Is this the first time starting the training? You might have missing gazebo models that the simulator is trying to load. What could be happening is that gazebo tries to load the world file and the models in it, but you do not have all the models available locally, so gazebo will download them. This takes some time and there are no indicators for this. 

You could try to open the world file directly in gazebo.
Alternatively, just start training and wait for some 20 to 30 minutes (it will download the models in the background), then see if the execution has started.

If this does not help, let me know.

**Comment by Ethan0207** [comment]
Hi，thank you for your reply. Today, I just start training and wait for some 20 to 30 minutes, but it has not start. And then I  try to open the world file directly in gazebo.
![12 29 2](https://github.com/reiniscimurs/DRL-robot-navigation/assets/138771150/692f8e59-6e67-4817-8697-106299244253)
![12 29 3](https://github.com/reiniscimurs/DRL-robot-navigation/assets/138771150/009a01aa-b268-4755-9b18-d37247143f72)
![12 29 1](https://github.com/reiniscimurs/DRL-robot-navigation/assets/138771150/8296a974-12a1-4427-ae98-2e4f1df0f6a2)
(additionally this is my TD_world.launch file)
![12 29 4](https://github.com/reiniscimurs/DRL-robot-navigation/assets/138771150/9c706f4d-6195-436c-b095-2b11a82d79a1)
but it still has not start.
![12 29 6](https://github.com/reiniscimurs/DRL-robot-navigation/assets/138771150/6956734d-0841-4ff0-949f-3ce2b38b1a31)
And I find annother question. When I "roslaunch multi_robot_scenario pioneer3dx.gazebo.launch", it just stop here.
![12 29 5](https://github.com/reiniscimurs/DRL-robot-navigation/assets/138771150/9485134d-4128-4671-8d41-e460c434d26e)
I must "conda deactivate" ,then the p3dx appears. Do you think that's a contributing factor?

**Comment by cd310105974** [comment]
The previously running node was not completely terminated. To kill the training process:
`killall -9 rosout roslaunch rosmaster gzserver nodelet robot_state_publisher gzclient python python3`

**Comment by reiniscimurs** [comment]
Hi,

as @cd310105974 pointed out the error message in one of the images most likely is because you did not properly kill your previous run.

For the main issue though, i would suggest to see if the way to source the locations is proper in your conda env as well. Especially, if you need to use "localhost". I can see that your gazebo simulator is not starting from calling it in the training script and the line `subprocess.Popen(["roslaunch", "-p", port, fullpath])` does not execute for you.

**Comment by Ethan0207** [comment]
Hi,
thank you for your reply. Firstly, I kill my previous run, but it is still failed.  I delete the commands in my bashrc file about conda and redo the steps . My ros still doesn't start. It is strange.
![1 2-1](https://github.com/reiniscimurs/DRL-robot-navigation/assets/138771150/7fbd3922-49a9-49cc-aa4f-c4143e521caa)

**Comment by reiniscimurs** [comment]
I'd suggest trying to set up the training without using a virtual env to see if it is specifically virtual env issue. Seems that there is some issue with setting up and running the repo in virtual env. I won't be able to set that up and test it anytime soon though.

**Comment by Ethan0207** [comment]
Thank you for your reply .I have solved the problem. I uninstall the Anaconda and install pytorch and tensorboard. It can work. I guess the version of ros and Anaconda clashed.
![1 3](https://github.com/reiniscimurs/DRL-robot-navigation/assets/138771150/e298d80e-f04c-4fcd-9a9e-cfa10db84cc7)
