### ISSUE TITLE
Gazebo environment

### ISSUE THREAD

**Issue by zichengS1999** [reiniscimurs/DRL-robot-navigation#98]
Is the simulation environment you created yourself or an existing open-source simulation environment?

**Comment by zichengS1999** [comment]
Thank you for your reply! Is this world file open-source and available for use? Can I use it to test my research direction, and can I cite it in my paper? Additionally, I have encountered an issue during my experiments where the robot in Rviz becomes unsynchronized and randomly teleports when I call the reset() function. Have you encountered a similar situation before?


https://github.com/reiniscimurs/DRL-robot-navigation/assets/116474299/6aada16d-217b-42c5-a8c3-a44b7b193595

**Comment by zichengS1999** [comment]
Thank you for your reply! Is this world file open-source and available for use? Can I use it to test my research direction, and can I cite it in my paper? Additionally, I have encountered an issue during my experiments where the robot in Rviz becomes unsynchronized and randomly teleports when I call the reset() function. Have you encountered a similar situation before?

**Comment by reiniscimurs** [comment]
You need to check the licenses in this and their repo, but you can use this for research. And yes, you should cite the paper where the world file is taken from.

Not sure what you mean by unsynchronized. Each reset call will randomly teleport the robot to a new location and star executing a new episode. That is how training is intended and done on purpose.

**Comment by zichengS1999** [comment]
The issue I encountered is the same as the first issue. It is like the two images below, where the robot's position changes from the first image to the second image after calling reset(). I also changed the robot and used a 2D laser.


![773cee9b7da620a6100f8a176dd727c](https://github.com/reiniscimurs/DRL-robot-navigation/assets/116474299/a6bf8838-51ac-46c8-ad3a-2ccb9b7941fa)
![ff1a65d9bd3e8b7b1c210b28d7c31a0](https://github.com/reiniscimurs/DRL-robot-navigation/assets/116474299/a6628abe-abd6-4dd0-8316-25f3aec92d0e)

**Comment by reiniscimurs** [comment]
Most likely it is an issue with transforms and might just be an issue with visualization in rviz. What is your fixed frame in rviz (under global options)? By default we use odom, but it might be different in your case if you have changed the robot model. You would have to look into your code to see what the proper transforms are.

**Comment by wxy666ustb** [comment]
Hello, I have also encountered this problem. May I ask how you solved it?
